<?php
namespace BCLib\LaravelHelpers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-05 at 01:42:06.
 */
class InputTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Input
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Input;
    }

    protected function tearDown()
    {
    }

    /**
     * @covers BCLib\LaravelHelpers\Input::get
     */
    public function testGetSingleParamsCorrectly()
    {
        $_SERVER['QUERY_STRING'] = 'foo=1&bar=2&foo=3&baz=4';
        $this->assertEquals(array('2'), Input::get('bar'));
    }

    /**
     * @covers BCLib\LaravelHelpers\Input::get
     */
    public function testGetMultipleParamsCorrectly()
    {
        $this->assertEquals(array('1', '3'), Input::get('foo'));
    }

    /**
     * @covers BCLib\LaravelHelpers\Input::has
     */
    public function testHasFindsName()
    {
        $this->assertTrue(Input::has('foo'));
    }

    /**
     * @covers BCLib\LaravelHelpers\Input::has
     */
    public function testHasReturnsFalseWhenNotPresent()
    {
        $this->assertFalse(Input::has('foobar'));
    }

    /**
     * @covers BCLib\LaravelHelpers\Input::all
     */
    public function testAllReturnsAll()
    {
        $this->assertEquals(['foo' => ['1', '3'], 'bar' => ['2'], 'baz' => ['4']], Input::all());
    }

    /**
     * @covers BCLib\LaravelHelpers\Input::only
     */
    public function testOnly()
    {
        $this->assertEquals(['foo' => ['1', '3'], 'bar' => ['2']], Input::only('foo', 'bar'));
    }

    /**
     * @covers BCLib\LaravelHelpers\Input::except
     */
    public function testExcept()
    {
        $this->assertEquals(['foo' => ['1', '3']], Input::except('bar', 'baz'));
    }
}
