<?php
namespace BCLib\DeepLinks;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-03 at 13:40:39.
 */
class BriefSearchTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BriefSearch
     */
    protected $object;

    /**
     * @covers BCLib\DeepLinks\BriefSearch::ISBN
     * @todo   Implement testISBN().
     */
    public function testISBN()
    {
        $this->isTrue(true);
    }
}
