<?php
namespace BCLib\DeepLinks;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-03 at 13:40:39.
 */
class BriefSearchTest extends \PHPUnit_Framework_TestCase
{

    public function testStringSetCorrectlygi()
    {
        $query = new \BCLib\PrimoTools\Query();
        $query->keyword('foobar');

        $scope = new \BCLib\PrimoTools\Scope('ONL');

        $object = new BriefSearch($query, $scope);

        $expected = 'http://bc-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?institution=BCL&vid=bclib&onCampus=true&group=GUEST&loc=local,scope:(ONL)&query=any,contains,foobar';
        $this->assertEquals($expected, (string) $object);
    }
}
