<?php
namespace BCLib\DeepLinks;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-06 at 14:25:19.
 */
class FullViewTest extends \PHPUnit_Framework_TestCase
{

    public function testFullViewWorks()
    {
        $expected = 'http://bc-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?institution=BCL&vid=bclib&onCampus=true&group=GUEST&docId=ALMA-BC21349370700001021';
        $object = new FullView('ALMA-BC21349370700001021');
        $this->assertEquals($expected, (string) $object);
    }
}
