<?php
namespace BCLib\PrimoTools;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-06 at 10:51:03.
 */
class ScopeListTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ScopeList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = ScopeList::instantiate();
    }

    public function testInstantiateReturnsScopeList()
    {
        $this->assertInstanceOf('\BCLib\PrimoTools\ScopeList', $this->object);
    }

    public function testGetScopeReturnsCorrectScopes()
    {
        $expected_scopes = array();

        $expected_scopes['bc'] = new Scope('BCL');
        $expected_scopes['archive'] = new Scope('ARCH');
        $expected_scopes['burns'] = new Scope('BURNS');
        $expected_scopes['bapst'] = new Scope('BAPST');
        $expected_scopes['gov'] = new Scope('GOV');
        $expected_scopes['weston'] = new Scope('GEO');
        $expected_scopes['media'] = new Scope('MEDIA');
        $expected_scopes['onl'] = new Scope('ONL');
        $expected_scopes['nedl'] = new Scope('NEDL');
        $expected_scopes['law'] = new Scope('LAW');
        $expected_scopes['pci'] = new Scope('pci');
        $expected_scopes['swk'] = new Scope('SWK');
        $expected_scopes['tml'] = new Scope('TML');
        $expected_scopes['icpsr'] = new Scope('bc_icpsr');
        $expected_scopes['erc'] = new Scope('ERC');
        $expected_scopes['stjc'] = new Scope('STJN');

        foreach ($expected_scopes as $name=>$expected_scope)
        {
            $this->assertEquals($expected_scope, $this->object->getScope($name));
        }
    }
}
