<?php
namespace BCLib\PrimoTools;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-06 at 10:51:03.
 */
class ScopeListTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ScopeList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = ScopeList::instantiate();
    }

    public function testInstantiateReturnsScopeList()
    {
        $this->assertInstanceOf('\BCLib\PrimoTools\ScopeList', $this->object);
    }
}
