<?php
namespace BCLib\PrimoTools;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-06 at 10:49:49.
 */
class ScopeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Scope
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new Scope('ONL');
    }

    public function testLocalScopeWorks()
    {
        $this->assertEquals('loc=local,scope:(ONL)', (string) $this->object);
    }

    public function testRemoteScopeWorks()
    {
        $this->object = new Scope('primo_central_multiple_fe', false);
        $this->assertEquals('loc=adaptor,primo_central_multiple_fe&tab=pci_only', (string) $this->object);
    }
}
